# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('meta', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('date', 'created_at'),
            },
        ),
    ]
