# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='name')),
                ('meta', models.CharField(blank=True, max_length=65, verbose_name='meta')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-date', 'created_at'),
            },
        ),
    ]
